moving tms search path to a config file

diff --git a/.local/bin/tms b/.local/bin/tms
--- a/.local/bin/tms
+++ b/.local/bin/tms
@@ -1,10 +1,20 @@
 #!/usr/bin/env bash
 
-selected=$( (find \
-	~/code \
+CONFIG_FILE="$HOME/.tms.conf"
+
+if [ -f "$CONFIG_FILE" ]; then
+    source "$CONFIG_FILE"
+else
+    echo "ERROR: Configuration file $CONFIG_FILE not found." >&2
+    exit 1
+fi
+
+selected=$(
+    (find "${SEARCH_PATHS[@]}" \
 	-mindepth 1 \
 	-maxdepth 1 \
-	-type d) | fzf)
+	-type d) | fzf
+)
 
 if [[ -z $selected ]]; then
     exit 0
